backend:
  name: github
  repo: adpe/portfolio

publish_mode: editorial_workflow

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "contributions"
    label: "Contributions"
    folder: "src/pages/contributions"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: ""
    fields:
      - {label: "Title", name: "title", required: true, widget: "string"}
      - {label: "Description", name: "description", required: true, widget: "text"}
      - {label: "Body", name: "body", required: true, widget: "markdown"}
      - {label: "Featured", name: "featured", required: false, widget: "boolean", default: true}
      - {label: "Tags", name: "tags", required: true, widget: "list"}
      - {label: "Image", name: "image", required: true, widget: "image"}
      - {label: "Link", name: "link", required: false, widget: "string"}
      - {label: "Weight", name: "weight", required: false, widget: "number", default: 400}
      - label: Sitemap
        name: sitemap
        widget: list
        fields:
        - {label: "Priority", name: "priority", required: false, widget: "number"}
  - name: "creations"
    label: "Creations"
    folder: "src/pages/creations"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: ""
    fields:
      - {label: "Title", name: "title", required: true, widget: "string"}
      - {label: "Description", name: "description", required: true, widget: "text"}
      - {label: "Body", name: "body", required: true, widget: "markdown"}
      - {label: "Featured", name: "featured", required: false, widget: "boolean", default: true}
      - {label: "Tags", name: "tags", required: true, widget: "list"}
      - {label: "Image", name: "image", required: true, widget: "image"}
      - {label: "Link", name: "link", required: false, widget: "string"}
      - {label: "Weight", name: "weight", required: false, widget: "number", default: 400}
  - name: "publications"
    label: "Publications"
    folder: "src/pages/publications"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: ""
    fields:
      - {label: "Title", name: "title", required: true, widget: "string"}
      - {label: "Publish Date", name: "date", required: true, widget: "datetime"}
      - {label: "Publish Type", name: "pubtype", required: false, widget: "string"}
      - {label: "Featured", name: "featured", required: false, widget: "boolean", default: false}
      - {label: "Description", name: "description", required: true, widget: "text"}
      - {label: "Body", name: "body", required: true, widget: "markdown"}
      - {label: "Tags", name: "tags", required: true, widget: "list"}
      - {label: "Image", name: "image", required: true, widget: "image"}
      - {label: "Link", name: "link", required: false, widget: "string"}
      - {label: "Weight", name: "weight", required: false, widget: "number", default: 400}
      - label: Sitemap
        name: sitemap
        widget: list
        fields:
        - {label: "Priority", name: "priority", required: false, widget: "number"}

